import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/provider/provider';
import { Roboto } from 'next/font/google';

const roboto = Roboto({
  weight: ['400', '900', '700', '500'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Next15 App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
